resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      products:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
    instances:
      products:
        base-config: default

server:
  port: 8090

spring:
  application:
    name: service-gateway-server
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
    gateway:
      routes:
        - id: service-items
          uri: lb://service-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request, 12345
            - AddResponseHeader=token-response, 12345678
            - AddRequestParameter=name, Jorge
        - id: service-products
          uri: lb://service-products
          predicates:
            - Path=/api/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: products
                statusCode: 500,404
                fallbackUri: forward:/api/items/v1/1/count/42
            - StripPrefix=2
            - name: Example
              args:
                message: Hi, my custom message
                cookieName: User
                cookieValue: JorgePinzon
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
