spring:
  application:
    name: service-products

server:
  port: 8001

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client-service-url:
    defaultZone: http://localhost:8761/eureka/
  client:
    register-with-eureka: true
    fetch-registry: true